### ISSUE TITLE
Typescript error on heading prop when using Tabs

### ISSUE THREAD

**Issue by adnanirfan** [GeekyAnts/react-native-boilerplate-redux-typescript#2]
I'm following this example, 
http://docs.nativebase.io/Components.html#tabs-advanced-headref

It should work like this, without any error
![native-base-bug](https://raw.githubusercontent.com/GeekyAnts/NativeBase-KitchenSink/v2.2.0/screenshots/android/tabs-advanced.gif)

But having this typescript error.
![native-base-bug](https://user-images.githubusercontent.com/9200214/32194117-3e5c2856-bddb-11e7-8ebb-e91879aaf12a.png)

versions: 
typescript: 2.5.2
npm: 5.5.1

**Comment by shivrajkumar** [comment]
@adnanirfan Some of the typings for `Tabs` seems to be missing in NativeBase. Report it in the NativeBase repo

**Comment by DustinEwan** [comment]
@shivrajkumar could you expand on what you mean by using your local types?  I've been stuck on problems w/ the Tabs typings for about two weeks now.  I need a stopgap until NativeBase publishes the fix.

Thanks!

**Comment by adnanirfan** [comment]
@DustinEwan I used it by type casting it 'as any' 
```javascript
<Tab
    heading={
        (
            <TabHeading>
                <Text>View</Text>
            </TabHeading>
        ) as any
    }
>
```

**Comment by shivrajkumar** [comment]
The above solution should work. And also you can just upgrade the NativeBase version to the latest, as the issue has been fixed.
